/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.curso.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Tarea service. Represents a row in the &quot;Gradle_Tarea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.curso.model.impl.TareaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.curso.model.impl.TareaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tarea
 * @see es.curso.model.impl.TareaImpl
 * @see es.curso.model.impl.TareaModelImpl
 * @generated
 */
@ProviderType
public interface TareaModel extends BaseModel<Tarea>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tarea model instance should use the {@link Tarea} interface instead.
	 */

	/**
	 * Returns the primary key of this tarea.
	 *
	 * @return the primary key of this tarea
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tarea.
	 *
	 * @param primaryKey the primary key of this tarea
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tarea.
	 *
	 * @return the uuid of this tarea
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this tarea.
	 *
	 * @param uuid the uuid of this tarea
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the tarea ID of this tarea.
	 *
	 * @return the tarea ID of this tarea
	 */
	public long getTareaId();

	/**
	 * Sets the tarea ID of this tarea.
	 *
	 * @param tareaId the tarea ID of this tarea
	 */
	public void setTareaId(long tareaId);

	/**
	 * Returns the group ID of this tarea.
	 *
	 * @return the group ID of this tarea
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this tarea.
	 *
	 * @param groupId the group ID of this tarea
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tarea.
	 *
	 * @return the company ID of this tarea
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tarea.
	 *
	 * @param companyId the company ID of this tarea
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tarea.
	 *
	 * @return the user ID of this tarea
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tarea.
	 *
	 * @param userId the user ID of this tarea
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tarea.
	 *
	 * @return the user uuid of this tarea
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tarea.
	 *
	 * @param userUuid the user uuid of this tarea
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the nombre tarea of this tarea.
	 *
	 * @return the nombre tarea of this tarea
	 */
	@AutoEscape
	public String getNombreTarea();

	/**
	 * Sets the nombre tarea of this tarea.
	 *
	 * @param nombreTarea the nombre tarea of this tarea
	 */
	public void setNombreTarea(String nombreTarea);

	/**
	 * Returns the descripcion tarea of this tarea.
	 *
	 * @return the descripcion tarea of this tarea
	 */
	@AutoEscape
	public String getDescripcionTarea();

	/**
	 * Sets the descripcion tarea of this tarea.
	 *
	 * @param descripcionTarea the descripcion tarea of this tarea
	 */
	public void setDescripcionTarea(String descripcionTarea);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tarea tarea);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tarea> toCacheModel();

	@Override
	public Tarea toEscapedModel();

	@Override
	public Tarea toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}